services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: dojo
      POSTGRES_PASSWORD: dojo
      POSTGRES_DB: fullstack_dojo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
